upstreamBbr:
  bbr:
    name: payload-processing
    replicas: 1
    image:
      registry: quay.io/rh-ee-aharush
      repository: llm-d-inference-sim
      tag: pp-perf-test
      pullPolicy: Always
    port: 9004
    healthCheckPort: 9005
    multiNamespace: true

    flags:
      # Log verbosity
      v: 3

    # BBR plugins configuration.
    # Format: type (registered plugin type), name (instance name), json (optional config object)
    plugins:
      - type: body-field-to-header
        name: model-extractor
        json:
          fieldName: model
          headerName: X-Gateway-Model-Name
      - type: model-provider-resolver
        name: model-provider-resolver
      - type: api-translation
        name: api-translation
      - type: apikey-injection
        name: apikey-injection

  provider:
    name: istio
    istio:
      envoyFilter:
        operation: INSERT_BEFORE

  inferenceGateway:
    name: maas-default-gateway
